version: "3"

services:
  # php
  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 3000:3000
      - 5173:5173
    expose:
      - 3000
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src

  # web
  web:
    image: nginx
    container_name: ${APP_NAME}_web
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - 8001:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3000
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M

  # mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"